name: Build Release

on:
  push:
    tags:
      - 'v*.*.*'    # Matches v4.11.0
      - '*.*.*'      # Matches 4.11.0
      - 'v*.*'       # Matches v4.11
      - '*.*'        # Matches 4.11

permissions:
  contents: write

jobs:
  run-checks:
    uses: ./.github/workflows/checks.yml
    
  build-release:
    needs: run-checks
    runs-on: ubuntu-latest
    environment: wordpress-org-repo
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Verify no uncommitted changes
        run: |
          if [[ -n $(git status -s) ]]; then
            echo "❌ ERROR: Uncommitted changes detected"
            echo "Please commit all changes before creating a release tag"
            git status -s
            exit 1
          fi
          echo "✅ Working directory is clean"
      
      - name: Get required PHP version
        id: php_version
        run: |
          PHP_VERSION=$(grep "Requires PHP:" clean-and-simple-contact-form-by-meg-nicholas/clean-and-simple-contact-form-by-meg-nicholas.php | awk '{print $3}')
          echo "PHP_VERSION=$PHP_VERSION" >> $GITHUB_OUTPUT
          echo "Plugin requires PHP $PHP_VERSION"
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ steps.php_version.outputs.PHP_VERSION }}
          tools: composer:v2, wp-cli
          
      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
        
      - name: Install WP-CLI dist-archive command
        run: wp package install wp-cli/dist-archive-command
        
      - name: Build plugin for release
        run: composer run-script build
          
      - name: Get version
        id: get_version
        run: |
          VERSION=$(grep "Version:" clean-and-simple-contact-form-by-meg-nicholas/clean-and-simple-contact-form-by-meg-nicholas.php | awk '{print $2}')
          echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          echo "Building version $VERSION"
          
      - name: Verify tag matches plugin version
        run: |
          # Get plugin version and tag version
          PLUGIN_VERSION=$(grep "Version:" clean-and-simple-contact-form-by-meg-nicholas/clean-and-simple-contact-form-by-meg-nicholas.php | awk '{print $2}')
          TAG_VERSION=${GITHUB_REF#refs/tags/}
          TAG_VERSION=${TAG_VERSION#v}  # Remove 'v' prefix if present
          
          echo "Plugin version: $PLUGIN_VERSION"
          echo "Git tag version: $TAG_VERSION"
          
          # Check if tag matches plugin version
          if [ "$PLUGIN_VERSION" != "$TAG_VERSION" ]; then
            echo "❌ ERROR: Version mismatch between plugin version ($PLUGIN_VERSION) and git tag ($TAG_VERSION)"
            exit 1
          fi
          
          echo "✅ Tag version matches plugin version: $PLUGIN_VERSION"
          
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }}
          name: Release ${{ steps.get_version.outputs.VERSION }}
          body: |
            Release of Clean and Simple Contact Form v${{ steps.get_version.outputs.VERSION }}
            
            ## What's New
            See [changelog](https://fullworksplugins.com/docs/clean-and-simple-contact-form/usage-clean-and-simple-contact-form/change-log-3/) for details.
            
            ## Key Features in v4.11
            - REST API support for headless WordPress
            - SMTP configuration via constants
            - Developer hooks for extensibility
            - Comprehensive documentation
            
            ## Installation
            Download the attached zip file and upload to your WordPress site via Plugins → Add New → Upload Plugin.
          draft: false
          prerelease: false
          files: |
            ./zipped/clean-and-simple-contact-form-by-meg-nicholas-free.zip#clean-and-simple-contact-form-${{ steps.get_version.outputs.VERSION }}.zip
          
      - name: Deploy to WordPress.org
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        run: |
          # Install subversion
          sudo apt-get update
          sudo apt-get install -y subversion
          
          # Extract plugin to temporary directory
          mkdir -p svn-tmp
          cd svn-tmp
          unzip ../zipped/clean-and-simple-contact-form-by-meg-nicholas-free.zip
          
          # Checkout SVN repository
          svn checkout https://plugins.svn.wordpress.org/clean-and-simple-contact-form-by-meg-nicholas/ svn-repo --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache
          
          # Copy files to trunk
          rsync -av --delete --exclude='.svn' clean-and-simple-contact-form-by-meg-nicholas/ svn-repo/trunk/
          
          # Add new files and remove deleted files
          cd svn-repo/trunk
          svn add --force * --auto-props --parents --depth infinity -q || true
          svn delete $( svn status | sed -e '/^!/!d' -e 's/^!//' ) || true
          
          # Copy to tags
          cd ..
          svn cp trunk tags/${{ steps.get_version.outputs.VERSION }}
          
          # Commit to SVN
          svn commit -m "Release version ${{ steps.get_version.outputs.VERSION }}" --username "$SVN_USERNAME" --password "$SVN_PASSWORD" --no-auth-cache
          
          echo "✅ Successfully deployed to WordPress.org"